### ISSUE TITLE
The type or namespace name `IAudioSource' could not be found. Are you missing an assembly reference?

### ISSUE THREAD

**Issue by jhd3197** [EnoxSoftware/NatCorderWithOpenCVForUnityExample#1]
<img width="2560" alt="screen shot 2018-09-10 at 10 31 40 am" src="https://user-images.githubusercontent.com/13461850/45303845-bced1f80-b4e4-11e8-8126-f86e68408df9.png">

**Comment by EnoxSoftware** [comment]
I've just fixed this issue.
Thank you for pointing it out.
