### ISSUE TITLE
NatShare version 1.2 'NatShareU' could not be found 	

### ISSUE THREAD

**Issue by PATolk** [EnoxSoftware/NatCorderWithOpenCVForUnityExample#4]
The current version on the asset store for nat share is Released: Dec 16, 2019 

The type or namespace name 'NatShareU' could not be found 	Assets\NatCorderWithOpenCVForUnityExample\VideoRecordingExample\VideoRecordingExample.cs

**Comment by EnoxSoftware** [comment]
There seems to be an issue with running the latest NatCorder and NatShare.
https://forum.unity.com/threads/natshare-free-sharing-api.527074/page-8#post-5291370
I will update the repository after the issue is fixed.

**Comment by EnoxSoftware** [comment]
Updated NatCorder version to 1.6.6.
Updated NatShare version to 1.2.1.
